<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.smartshaped.chameleon.reviews</groupId>
  <artifactId>speed</artifactId>
  <version>0.0.1</version>
  <name>speed-reviews</name>
  <description>Speed Layer App for Reviews</description>
  
    <properties>
        <java.version>11</java.version>
	    <spark-version>3.5.1</spark-version>
	    <lombok-version>1.18.26</lombok-version>
	    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	    <maven.compiler.source>11</maven.compiler.source>
	    <maven.compiler.target>11</maven.compiler.target>
		<chameleon.version>1.0.0</chameleon.version>
    </properties>

	<dependencies>
		<dependency>
			<groupId>com.smartshaped.chameleon</groupId>
			<artifactId>speed</artifactId>
			<version>${chameleon.version}</version>
		</dependency>
    	
    	<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
			<version>${lombok-version}</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>speed-reviews-${project.version}</finalName>
		<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Specification-Title> Java Advanced Imaging Image I/O Tools</Specification-Title>
                                        <Specification-Version>1.1</Specification-Version>
                                        <Specification-Vendor> Sun Microsystems, Inc. </Specification-Vendor>
                                        <Implementation-Title> com.sun.media.imageio</Implementation-Title>
                                        <Implementation-Version> 1.1</Implementation-Version>
                                        <Implementation-Vendor> Sun Microsystems, Inc.</Implementation-Vendor>
                                        <Multi-Release>true</Multi-Release>
                                    </manifestEntries>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
</project>