speed:
  spark:
    app:
      name: "speed-reviews"
    yarn:
      am:
        cores: 1
        memory: "640m"
        memoryOverhead: "384m"
    driver:
      memory: "1024m"
      cores: 2
      maxResultSize: "1024m"
    executor:
      memory: "2688m"
      instances: 2
      cores: 2
      memoryOverhead: "384m"
      heartbeatInterval: 60
    serializer: "org.apache.spark.serializer.KryoSerializer"
    memory:
      fraction: 0.75
      storageFraction: 0.5
    sql:
      parquet:
        compression:
          codec: "zstd"
      shuffle:
        partitions: 200
    cassandra:
      connection:
        host: "cassandra1"
        port: 9042
        timeoutMS: "10000"
      read:
        timeoutMS: "10000"
    hadoop:
      fs:
        defaultFS: "hdfs://namenode:8020"
      parquet:
        page:
          size:
            row:
              check:
                min: 2
                max: 10
      dfs:
        replication: 1
  kafka:
    server: "kafka1:19092"
    bootstrap-servers: kafka1:19092
    intervalMs: "20000"
    producer:
      bootstrap-servers: kafka1:19092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      topic1:
        name: "topicReviews"
        class: "com.smartshaped.chameleon.reviews.utils.ReviewPreprocessor"
        path: "/user/spark/topicReviews/data.parquet"
        checkpoint: "/user/spark/checkpoint/topicReviews"
  updater:
    name: "TrendingReviewsUpdater"
    class: "com.smartshaped.chameleon.reviews.speed.components.TrendingReviewsUpdater"
  cassandra:
    node: "cassandra1"
    port: 9042
    datacenter: "datacenter1"
    checkpoint: "/user/spark/checkpoint/cassandra/speed"
    keyspace: 
      name: "fesr_test"
    model:
      class: "com.smartshaped.chameleon.reviews.speed.utils.TrendingModel"
